version: '3.7'

services:
  db:
    image: postgres:12.0-alpine

    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=zvonok

  redis:
    image: redis:latest
    ports:
      - 6379:6379
  web:
    build: .
    command: bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    env_file:
      - ./backend/config/.env
    depends_on:
      - db
    links:
      - db
  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app/
    depends_on:
      - redis
      - web
