version: '3.7'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./backend/config/.env
  celery:
    build: .
    command: celery -A config worker -l info
    depends_on:
      - redis
      - web